version: '2.1'
orbs:
  rust: circleci/rust@1.6.0
workflows:
  production:
    jobs:
      - fix_edition:
        - steps:
          - checkout # check out the code in the project directory
          - run: cargo fix --edition # run the `echo` command
      - rust/lint-test-build:
          release: true
          requires:
            - my_test_job
          