version: 2.1
# remove this orb, or keep as a placeholder for another
orbs:
  rust: circleci/rust@1.6.0
jobs:
  lint_test_build:
    docker:
      - image: neosb/nutek-core:latest
    steps:
      - run: apt update
      - run: apt -y install \
              ca-certificates \
              curl \
              gnupg \
              lsb-release
      - run: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: apt update
      - run: apt -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - checkout
      - run: cargo fix --edition
      - run: rustup component add clippy
      - run: cargo clippy
      - run: cargo test
      - run: cargo build  --release
workflows:
  production:
    jobs:
      - lint_test_build
