version: 2.1
# remove this orb, or keep as a placeholder for another
orbs:
  rust: circleci/rust@1.6.0
jobs:
  lint_test_build:
    docker:
      - image: neosb/nutek-core:latest
    steps:
      - checkout
      - run: cargo fix --edition
      - run: rustup component add clippy
      - run: cargo clippy
      - run: cargo test
      - run: cargo build  --release
workflows:
  production:
    jobs:
      - lint_test_build
