version: 2.1
# remove this orb, or keep as a placeholder for another
orbs:
  rust: circleci/rust@1.6.0
jobs:
  lint_test_build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run: sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg lsb-release
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
      - run: docker pull neosb/nutek-core:latest
      - run: export PATH="/root/.cargo/bin:$PATH"
      - run: sudo apt-get -y install build-essential
      - checkout
      - run: cargo fix --edition
      - run: rustup component add clippy
      - run: cargo clippy
      - run: cargo test
      - run: cargo build  --release
  # not available for free
  # windows:
  #   machine:
  #     image: windows-server-2019-vs2019:current
  #   steps:
  #     - checkout
  #     - run: curl -Uri https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe
  #     - run: .\rustup-init.exe --default-toolchain stable -y
  #     - run: .\rustc --version
  # mac_os:
  #   macos:
  #     xcode: 13.3.0
  #   steps:
  ##     /bin/bash: docker: command not found
  #     - run: docker pull neosb/nutek-core:latest
  #     - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
  #     - run: export PATH="/root/.cargo/bin:$PATH"
  #     - checkout
  #     - run: cargo fix --edition
  #     - run: rustup component add clippy
  #     - run: cargo clippy
  #     - run: cargo test
  #     - run: cargo build  --release
workflows:
  production:
    jobs:
      - lint_test_build