version: '2.1'
orbs:
  rust: circleci/rust@1.6.0
workflows:
  production:
    jobs:
      - if-good:
        steps:
          - checkout # check out the code in the project directory
          - run: 
            command: cargo fix --edition # run the `echo` command
          - rust/lint-test-build:
            release: true
          