version: 2.1
# remove this orb, or keep as a placeholder for another
orbs:
  rust: circleci/rust@1.6.0
jobs:
  lint_test_build:
    docker:
      - image: neosb/nutek-core:latest
    steps:
      - run: mkdir -p $HOME/.nutek/rustscan/nmap
      - run: printf '%s\n' "deb https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker-ce.list
      - run: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-ce-archive-keyring.gpg
      - run: apt update && apt -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - checkout
      - run: cargo fix --edition
      - run: rustup component add clippy
      - run: cargo clippy
      - run: cargo test
      - run: cargo build  --release
workflows:
  production:
    jobs:
      - lint_test_build
